language: node_js
node_js:
  - "0.8"
  - "0.9"

services:
  - couchdb

before_script:
  - npm install -g grunt-cli
  - curl -X PUT http://127.0.0.1:5984/foobar
  - curl -X PUT http://127.0.0.1:5984/_config/admins/stefan --data '"xxxx"'¬
