language: node_js
node_js:
  - "0.8"
  - "0.9"
  - "0.10"

branches:
  only:
    - master

before_script:
  - npm install -g grunt-cli

notifications:
  webhooks: http://limitless-badlands-1553.herokuapp.com/builds
